# Copyright (c) 2026, BrainWise and contributors
# For license information, please see license.txt

"""
Discount Restriction enforcement for POS invoices.

A `POS Discount Restriction` rule gates manual discounts (item-level and
additional) for the companies listed (and enabled) on the rule, within the
rule's date window, optionally enforcing a transaction quota (shared or
per company) and one-time confirmation codes generated by head office.

Enforcement points (doc_events on Sales Invoice):
- validate:  hard gate on draft save AND submit (window, company scope, quota,
             confirmation code readable/available). Also stamps
             `pos_discount_restriction` on the invoice for audit.
- on_submit: consume quota (ledger row) and claim the confirmation code —
             atomically, inside the submit transaction, so a failed claim
             rolls the whole submit back.
- on_cancel: delete the ledger rows (release the quota). Codes stay Used.

Offer/coupon-driven item discounts are indistinguishable from manual ones at
this layer (pricing_rules is cleared before save), so they are governed too.
"""

import frappe
from frappe import _
from frappe.utils import cint, flt, now_datetime, today

RESTRICTION_DOCTYPE = "POS Discount Restriction"
COMPANY_CHILD_DOCTYPE = "POS Discount Restriction Company"
CODE_DOCTYPE = "POS Discount Confirmation Code"
USAGE_DOCTYPE = "POS Discount Restriction Usage"


# ==========================================================================
# Rule resolution
# ==========================================================================


def get_applicable_restriction(company, posting_date=None):
	"""Return the single active rule for company + date, or None.

	A rule applies when it is enabled, the date falls inside its window, and
	the company has an enabled row on it. More than one match is an ambiguous
	configuration — raise so head office fixes the rules instead of POS
	guessing which one was meant.
	"""
	if not company:
		return None

	date = posting_date or today()
	rows = frappe.get_all(
		RESTRICTION_DOCTYPE,
		filters={"enabled": 1, "valid_from": ["<=", date], "valid_to": [">=", date]},
		fields=["name", "title"],
		order_by="name",
	)
	if not rows:
		return None

	names = [row.name for row in rows]
	matched = set(
		frappe.get_all(
			COMPANY_CHILD_DOCTYPE,
			filters={
				"parent": ["in", names],
				"parenttype": RESTRICTION_DOCTYPE,
				"enabled": 1,
				"company": company,
			},
			pluck="parent",
		)
	)

	if not matched:
		return None
	if len(matched) > 1:
		titles = ", ".join(row.title for row in rows if row.name in matched)
		frappe.throw(
			_(
				"Multiple discount restriction rules are active for company {0} on {1}: {2}. "
				"Please ask head office to fix the overlapping rules."
			).format(company, date, titles)
		)

	return frappe.get_doc(RESTRICTION_DOCTYPE, matched.pop())


# ==========================================================================
# Discount detection
# ==========================================================================


def _item_has_discount(item):
	"""True when the item row carries a manual discount (incl. a manual rate
	edit below price_list_rate, which is a discount in disguise)."""
	if flt(item.get("discount_percentage") or 0) > 0 or flt(item.get("discount_amount") or 0) > 0:
		return True

	if cint(item.get("is_rate_manually_edited") or 0):
		price_list_rate = flt(item.get("price_list_rate") or 0)
		rate = flt(item.get("rate") or 0)
		if price_list_rate > 0 and rate < price_list_rate:
			return True

	return False


def invoice_has_manual_discount(doc):
	"""True when the invoice discounts anything: any item row, or the header
	additional discount."""
	if flt(doc.get("discount_amount") or 0) > 0:
		return True

	return any(_item_has_discount(item) for item in (doc.get("items") or []))


def invoice_requires_code(rule, doc):
	"""True when the rule's confirmation-code requirement covers this invoice.

	With an item list on the rule, only discounts on those items (or the
	additional discount, which hits the whole cart) demand a code; an empty
	list means every discounted item does.
	"""
	if not cint(rule.require_confirmation_code):
		return False

	if flt(doc.get("discount_amount") or 0) > 0:
		return True

	listed = {row.item for row in (rule.get("code_items") or [])}
	for item in doc.get("items") or []:
		if not _item_has_discount(item):
			continue
		if not listed or item.get("item_code") in listed:
			return True

	return False


# ==========================================================================
# Quota
# ==========================================================================


def get_quota_info(rule, company):
	"""Return {mode, limit, used, remaining} or None when quota isn't enforced.

	`remaining` is None for an unlimited quota (limit 0).
	"""
	if not cint(rule.enforce_usage_quota):
		return None

	if rule.quota_mode == "Global":
		limit = cint(rule.global_max_usage)
		used = frappe.db.count(USAGE_DOCTYPE, {"restriction": rule.name})
	else:
		limit = 0
		for row in rule.get("companies") or []:
			if row.company == company:
				limit = cint(row.max_usage)
				break
		used = frappe.db.count(USAGE_DOCTYPE, {"restriction": rule.name, "company": company})

	remaining = None if limit <= 0 else max(limit - used, 0)
	return {"mode": rule.quota_mode, "limit": limit, "used": used, "remaining": remaining}


def check_quota(rule, company):
	"""Raise ValidationError when the quota for this rule/company is used up."""
	info = get_quota_info(rule, company)
	if not info or info["remaining"] is None:
		return info

	if info["remaining"] == 0:
		if info["mode"] == "Global":
			frappe.throw(
				_("Discount quota for rule {0} is used up ({1} of {2} transactions across all companies).").format(
					rule.title, info["used"], info["limit"]
				)
			)
		frappe.throw(
			_("Discount quota for rule {0} is used up for company {1} ({2} of {3} transactions).").format(
				rule.title, company, info["used"], info["limit"]
			)
		)
	return info


# ==========================================================================
# Confirmation codes
# ==========================================================================


def _validate_code_value(rule, code_value, company):
	"""Read-only code validation. Returns the code document name; raises a
	precise ValidationError on any problem."""
	code_value = (code_value or "").strip().upper()
	if not code_value:
		frappe.throw(
			_("A confirmation code from head office is required for this discount (rule {0}).").format(
				rule.title
			)
		)

	row = frappe.db.get_value(
		CODE_DOCTYPE,
		{"code": code_value, "restriction": rule.name},
		["name", "status", "company"],
		as_dict=True,
	)
	if not row:
		frappe.throw(_("Confirmation code {0} is not valid for rule {1}.").format(code_value, rule.title))
	if row.status == "Used":
		frappe.throw(_("Confirmation code {0} has already been used.").format(code_value))
	if row.status == "Cancelled":
		frappe.throw(_("Confirmation code {0} has been cancelled.").format(code_value))
	if row.company and company and row.company != company:
		frappe.throw(_("Confirmation code {0} is not valid for company {1}.").format(code_value, company))

	return row.name


def claim_code(rule, code_value, company, invoice_name):
	"""Claim a code atomically for this invoice.

	Holds a row lock on the code between the read and the status flip, so two
	submits racing on the same code cannot both win; the flip happens inside
	the submit transaction, so a later failure rolls the claim back too.
	"""
	code_name = _validate_code_value(rule, code_value, company)

	row = frappe.db.get_value(CODE_DOCTYPE, code_name, ["status", "company"], as_dict=True, for_update=True)
	if row.status != "Available":
		frappe.throw(_("Confirmation code is no longer available ({0}).").format(row.status))

	# Deliberate db-level flip: the claim must be race-safe and rollback with
	# the submit transaction; document-level save would re-run validations and
	# cannot take the row lock.
	frappe.db.set_value(
		CODE_DOCTYPE,
		code_name,
		{
			"status": "Used",
			"used_by": frappe.session.user,
			"used_in_invoice": invoice_name,
			"used_on": now_datetime(),
		},
	)


# ==========================================================================
# doc_events (Sales Invoice)
# ==========================================================================


def validate_invoice_discounts(doc, method=None):
	"""Sales Invoice validate hook — the hard gate (draft save and submit)."""
	if not doc.get("is_pos") or doc.get("is_return"):
		return
	if not invoice_has_manual_discount(doc):
		return

	rule = get_applicable_restriction(doc.get("company"), doc.get("posting_date"))
	if not rule:
		return

	check_quota(rule, doc.get("company"))
	doc.set("pos_discount_restriction", rule.name)

	if invoice_requires_code(rule, doc):
		_validate_code_value(rule, doc.get("discount_confirmation_code"), doc.get("company"))


def record_usage_on_submit(doc, method=None):
	"""Sales Invoice on_submit hook — consume quota and claim the code."""
	if not doc.get("is_pos") or doc.get("is_return"):
		return
	if not invoice_has_manual_discount(doc):
		return

	rule = get_applicable_restriction(doc.get("company"), doc.get("posting_date"))
	if not rule:
		return

	company = doc.get("company")

	# Serialize concurrent submits racing for the last quota slot or the same
	# code: hold the rule row until this transaction commits.
	frappe.db.get_value(RESTRICTION_DOCTYPE, rule.name, "name", for_update=True)

	check_quota(rule, company)

	try:
		frappe.get_doc(
			{
				"doctype": USAGE_DOCTYPE,
				"restriction": rule.name,
				"company": company,
				"sales_invoice": doc.get("name"),
				"used_by": frappe.session.user,
				"used_on": now_datetime(),
			}
		).insert(ignore_permissions=True, ignore_if_duplicate=True)
	except frappe.DuplicateEntryError:
		pass

	doc.set("pos_discount_restriction", rule.name)

	if invoice_requires_code(rule, doc):
		claim_code(rule, doc.get("discount_confirmation_code"), company, doc.get("name"))


def release_usage_on_cancel(doc, method=None):
	"""Sales Invoice on_cancel hook — release the consumed quota."""
	frappe.db.delete(USAGE_DOCTYPE, {"sales_invoice": doc.get("name")})
